HOST_IP = "localhost"
USER = "root"
PASSWORD = "1999923"
GROUP_NAME = "GroupA"
DEVICE_ID = "DeviceA"

MQTT_HOSTNAME = "nam1.cloud.thethings.network"
MQTT_USERNAME = "4id3-data-collection@ttn"
MQTT_API_KEY = "NNSXS.EXIXYQX3XLMNE3RF4L35MM2AY5XUEW2Y6TMPOYI.QSWBX7YCGIJJSCXOV4XNBJMP73FZ3ALBX4JZAMW4HACTYZLERSCA"
MQTT_PORT = 1883
MQTT_TOPIC = "#"

